In [1]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures , StandardScaler
from sklearn.metrics import mean_absolute_error , mean_squared_error , r2_score
from sklearn.metrics import accuracy_score , confusion_matrix , classification_report
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
from sklearn.datasets import load_wine

In [3]:
#Q263
wine = load_wine()
x = wine.data
y = wine.target

x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.3 , random_state=42)
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(x_train,y_train)
y_pred = knn.predict(x_test)

print(accuracy_score(y_test , y_pred))

0.7407407407407407


In [4]:
#Q264

wine = load_wine()

x = wine.data
y = wine.target

x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.3 , random_state=42)
dt = DecisionTreeClassifier(criterion='entropy' , random_state=42)
dt.fit(x_train , y_train)
y_pred = dt.predict(x_test)

print(confusion_matrix(y_test , y_pred))

[[18  1  0]
 [ 2 17  2]
 [ 2  1 11]]


In [5]:
#Q265
wine = load_wine()

x = wine.data
y = wine.target

x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.3 , random_state=42)
dt = DecisionTreeClassifier(criterion='entropy' , random_state=42)
dt.fit(x_train , y_train)
y_pred = dt.predict(x_test)

print(classification_report(y_test , y_pred))
print(accuracy_score(y_test , y_pred))

              precision    recall  f1-score   support

           0       0.82      0.95      0.88        19
           1       0.89      0.81      0.85        21
           2       0.85      0.79      0.81        14

    accuracy                           0.85        54
   macro avg       0.85      0.85      0.85        54
weighted avg       0.86      0.85      0.85        54

0.8518518518518519


In [6]:
#Q266
df = pd.read_csv('iris.csv')
df.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [7]:
x = df.drop(['Species'] , axis=1)
y = df['Species']

x_train , x_test , y_train , y_test = train_test_split(x,y , test_size=0.2 , random_state=42)

knn = KNeighborsClassifier(n_neighbors=3)

knn.fit(x_train , y_train)
y_pred = knn.predict(x_test)

print(accuracy_score(y_test , y_pred))

1.0


In [8]:
#Q267
df = pd.read_csv('diabetes.csv')
df.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [9]:
x = df.drop(['Outcome'] , axis=1)
y = df['Outcome']

x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.2 , random_state=42)

knn = KNeighborsClassifier(n_neighbors=5)

knn.fit(x_train , y_train)
y_pred = knn.predict(x_test)

print(accuracy_score(y_test , y_pred))
print(confusion_matrix(y_test , y_pred))

0.6623376623376623
[[70 29]
 [23 32]]


In [10]:
#Q268
df = pd.read_csv('cancer.csv')
df.columns

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst', 'Unnamed: 32'],
      dtype='object')

In [11]:
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN


In [12]:
df = df.drop(['Unnamed: 32'],axis=1)
x = df.drop(['diagnosis'] , axis=1)
y = df['diagnosis']

x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.3 , random_state=42)
scalar = StandardScaler()
x_train_scale = scalar.fit_transform(x_train)
x_test_scale = scalar.transform(x_test)
knn = KNeighborsClassifier(n_neighbors=5)

knn.fit(x_train_scale , y_train)

y_pred = knn.predict(x_test_scale)
print(accuracy_score(y_test , y_pred))
print(classification_report(y_test , y_pred))
print(confusion_matrix(y_test , y_pred))

0.9590643274853801
              precision    recall  f1-score   support

           B       0.96      0.97      0.97       108
           M       0.95      0.94      0.94        63

    accuracy                           0.96       171
   macro avg       0.96      0.95      0.96       171
weighted avg       0.96      0.96      0.96       171

[[105   3]
 [  4  59]]


C:\ProgramData\anaconda3\Lib\site-packages\joblib\externals\loky\backend\context.py:136: UserWarning: Could not find the number of physical cores for the following reason:
[WinError 2] The system cannot find the file specified
Returning the number of logical cores instead. You can silence this warning by setting LOKY_MAX_CPU_COUNT to the number of cores you want to use.
  warnings.warn(
  File "C:\ProgramData\anaconda3\Lib\site-packages\joblib\externals\loky\backend\context.py", line 257, in _count_physical_cores
    cpu_info = subprocess.run(
        "wmic CPU Get NumberOfCores /Format:csv".split(),
        capture_output=True,
        text=True,
    )
  File "C:\ProgramData\anaconda3\Lib\subprocess.py", line 554, in run
    with Popen(*popenargs, **kwargs) as process:
         ~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\subprocess.py", line 1039, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^

In [13]:
#Q269
df = pd.read_csv('card_transdat.csv')
df.columns

Index(['distance_from_home', 'distance_from_last_transaction',
       'ratio_to_median_purchase_price', 'repeat_retailer', 'used_chip',
       'used_pin_number', 'online_order', 'fraud'],
      dtype='object')

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 8 columns):
 #   Column                          Non-Null Count    Dtype  
---  ------                          --------------    -----  
 0   distance_from_home              1000000 non-null  float64
 1   distance_from_last_transaction  1000000 non-null  float64
 2   ratio_to_median_purchase_price  1000000 non-null  float64
 3   repeat_retailer                 1000000 non-null  float64
 4   used_chip                       1000000 non-null  float64
 5   used_pin_number                 1000000 non-null  float64
 6   online_order                    1000000 non-null  float64
 7   fraud                           1000000 non-null  float64
dtypes: float64(8)
memory usage: 61.0 MB


In [15]:
x = df.drop(['fraud'] ,axis=1)
y = df['fraud']

x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.3 , random_state=42)

knn = KNeighborsClassifier(n_neighbors=5)

knn.fit(x_train , y_train)

y_pred = knn.predict(x_test)

print(accuracy_score(y_test , y_pred))
print(confusion_matrix(y_test , y_pred))
print(classification_report(y_test , y_pred))

0.98291
[[270679   3192]
 [  1935  24194]]
              precision    recall  f1-score   support

         0.0       0.99      0.99      0.99    273871
         1.0       0.88      0.93      0.90     26129

    accuracy                           0.98    300000
   macro avg       0.94      0.96      0.95    300000
weighted avg       0.98      0.98      0.98    300000



In [16]:
# with standard scale 
x = df.drop(['fraud'] ,axis=1)
y = df['fraud']

x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.3 , random_state=42)

knn = KNeighborsClassifier(n_neighbors=5)
scalar = StandardScaler()

x_train_scale = scalar.fit_transform(x_train)
x_test_scale = scalar.transform(x_test)

knn.fit(x_train_scale , y_train)

y_pred = knn.predict(x_test_scale)

print(accuracy_score(y_test , y_pred))
print(confusion_matrix(y_test , y_pred))
print(classification_report(y_test , y_pred))

0.99869
[[273741    130]
 [   263  25866]]
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00    273871
         1.0       0.99      0.99      0.99     26129

    accuracy                           1.00    300000
   macro avg       1.00      0.99      1.00    300000
weighted avg       1.00      1.00      1.00    300000



In [17]:
#Q270
df = pd.read_csv('AQI and Lat Long of Countries.csv')
df.columns

Index(['Country', 'City', 'AQI Value', 'AQI Category', 'CO AQI Value',
       'CO AQI Category', 'Ozone AQI Value', 'Ozone AQI Category',
       'NO2 AQI Value', 'NO2 AQI Category', 'PM2.5 AQI Value',
       'PM2.5 AQI Category', 'lat', 'lng'],
      dtype='object')

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16695 entries, 0 to 16694
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Country             16393 non-null  object 
 1   City                16695 non-null  object 
 2   AQI Value           16695 non-null  int64  
 3   AQI Category        16695 non-null  object 
 4   CO AQI Value        16695 non-null  int64  
 5   CO AQI Category     16695 non-null  object 
 6   Ozone AQI Value     16695 non-null  int64  
 7   Ozone AQI Category  16695 non-null  object 
 8   NO2 AQI Value       16695 non-null  int64  
 9   NO2 AQI Category    16695 non-null  object 
 10  PM2.5 AQI Value     16695 non-null  int64  
 11  PM2.5 AQI Category  16695 non-null  object 
 12  lat                 16695 non-null  float64
 13  lng                 16695 non-null  float64
dtypes: float64(2), int64(5), object(7)
memory usage: 1.8+ MB


In [19]:
x = df[['lat','lng']]
y = df['AQI Value']

x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.2 , random_state=42)
knn = KNeighborsClassifier(n_neighbors=5)

knn.fit(x_train , y_train)

y_pred = knn.predict(x_test)

print(mean_absolute_error(y_test , y_pred))
print(mean_squared_error(y_test , y_pred))
print(r2_score(y_test , y_pred))
print(knn.predict([[40.7128, -74.0060]]))

20.772386942198263
1287.6786463012877
0.22359587398098268
[73]


C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


In [2]:
#Q271
df = pd.read_csv('PlayTennis.csv')
df.columns

Index(['outlook', 'temp', 'humidity', 'windy', 'play'], dtype='object')

In [3]:
x = pd.get_dummies(df.drop(['play'] , axis=1))
y = df['play']

x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.2 , random_state=42)

dt = DecisionTreeClassifier(random_state=42)

dt.fit(x_train , y_train)

y_pred = dt.predict(x_test)

print(accuracy_score(y_test , y_pred))
print(confusion_matrix(y_test , y_pred))
print(classification_report(y_test , y_pred))

1.0
[[1 0]
 [0 2]]
              precision    recall  f1-score   support

          no       1.00      1.00      1.00         1
         yes       1.00      1.00      1.00         2

    accuracy                           1.00         3
   macro avg       1.00      1.00      1.00         3
weighted avg       1.00      1.00      1.00         3



In [78]:
#Q272
df = pd.read_csv('drug200.csv')
df.columns

Index(['Age', 'Sex', 'BP', 'Cholesterol', 'Na_to_K', 'Drug'], dtype='object')

In [79]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Age          200 non-null    int64  
 1   Sex          200 non-null    object 
 2   BP           200 non-null    object 
 3   Cholesterol  200 non-null    object 
 4   Na_to_K      200 non-null    float64
 5   Drug         200 non-null    object 
dtypes: float64(1), int64(1), object(4)
memory usage: 9.5+ KB


In [80]:
x = pd.get_dummies(df.drop(['Drug'] , axis=1) , drop_first=True)
y = df['Drug']

x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.2 , random_state=42)

dt = DecisionTreeClassifier(random_state=42 ,criterion='entropy')
dt.fit(x_train , y_train)
y_pred = dt.predict(x_test)

print(accuracy_score(y_test , y_pred))
print(confusion_matrix(y_test , y_pred))
print(classification_report(y_test , y_pred))

1.0
[[ 6  0  0  0  0]
 [ 0  3  0  0  0]
 [ 0  0  5  0  0]
 [ 0  0  0 11  0]
 [ 0  0  0  0 15]]
              precision    recall  f1-score   support

       drugA       1.00      1.00      1.00         6
       drugB       1.00      1.00      1.00         3
       drugC       1.00      1.00      1.00         5
       drugX       1.00      1.00      1.00        11
       drugY       1.00      1.00      1.00        15

    accuracy                           1.00        40
   macro avg       1.00      1.00      1.00        40
weighted avg       1.00      1.00      1.00        40



In [76]:
#Q273

df = pd.read_csv('StudentsPerformance.csv')
def grade(x):
    if x>=50:
        return 1
    else:
        return 0
df['math'] = df['math score'].apply(grade)
df['reading']=df['reading score'].apply(grade)
df['writing']=df['writing score'].apply(grade)

df = df.drop(['math score' , 'reading score' , 'writing score'] , axis=1)

df['Overall_pass'] = np.where((df['math']==1)&(df['reading']==1)&(df['writing']==1) , 1 ,0)

x = pd.get_dummies(df.drop(['math'],axis=1), columns=['gender','race/ethnicity', 'parental level of education', 'lunch','test preparation course'] , drop_first=True)
df = df.dropna()
y = df['math']

x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.2 , random_state=42)

dt = DecisionTreeClassifier(random_state=42 ,criterion='entropy')
dt.fit(x_train , y_train)
y_pred = dt.predict(x_test)

print(accuracy_score(y_test , y_pred))
print(confusion_matrix(y_test , y_pred))

0.935
[[ 28   6]
 [  7 159]]


In [84]:
#Q310

df = pd.read_csv('cancer.csv')

df = df.drop(['Unnamed: 32']  ,axis=1)

In [85]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 32 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       569 non-null    int64  
 1   diagnosis                569 non-null    object 
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             5

In [95]:
x = df.drop(['diagnosis'] , axis=1)
y = df['diagnosis']
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.25 ,random_state=10)

svm = SVC(kernel='rbf' , random_state=10)
svm.fit(x_train , y_train)
y_pred = svm.predict(x_test)

print(accuracy_score(y_test , y_pred))
print(confusion_matrix(y_test , y_pred))

0.6223776223776224
[[89  2]
 [52  0]]


In [104]:
#Q311
df = pd.read_csv('diabetes.csv')
x = df.drop(['Outcome'] , axis=1)
y = df['Outcome']

x_train , x_test , y_train ,y_test = train_test_split(x,y,test_size=0.25 , random_state=10)

rf = RandomForestClassifier(n_estimators=100 , random_state=10)

rf.fit(x_train , y_train)

y_pred = rf.predict(x_test)

print(accuracy_score(y_test , y_pred))
print(confusion_matrix(y_test , y_pred))

0.765625
[[109  12]
 [ 33  38]]


In [105]:
#Q312

df = pd.read_csv('iris.csv')
df.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [106]:
x = df.drop(['Species'], axis=1)
y = df['Species']

x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.2 , random_state=42)

svm = SVC(C=1 , random_state=42)
svm.fit(x_train , y_train)
y_pred = svm.predict(x_test)

print(accuracy_score(y_test , y_pred))
print(confusion_matrix(y_test , y_pred))

1.0
[[12  0]
 [ 0  8]]


In [ ]:
#Q313

df = pd.read_csv